name: Merge
on:
  pull_request_target:
jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          target: minor
