name: Test
on:
  push:
    branches: ["*"]
    tags-ignore: ["*"]
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          cd docs
          yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn eslint .

      - name: Build library
        run: yarn build

      - name: Build documents
        run: |
          cd docs
          yarn build
